import 'package:chaining/Classes/AssetCoin.dart';
import 'package:chaining/Classes/User.dart';

var dictonaryOfAllAssets = {
  "bitcoin",
  "ethereum",
  "tether",
  "usd-coin",
  "binance-coin",
  "binance-usd",
  "cardano",
  "xrp",
  "solana",
  "dogecoin",
  "polkadot",
  "multi-collateral-dai",
  "polygon",
  "avalanche",
  "terra-luna",
  "shiba-inu",
  "tron",
  "wrapped-bitcoin",
  "uniswap",
  "unus-sed-leo",
  "litecoin",
  "ftx-token",
  "ethereum-classic",
  "near-protocol",
  "chainlink",
  "crypto-com-coin",
  "stellar",
  "monero",
  "cosmos",
  "bitcoin-cash",
  "bitcoin-bep2",
  "algorand",
  "vechain",
  "filecoin",
  "internet-computer",
  "decentraland",
  "the-sandbox",
  "tezos",
  "theta",
  "quant",
  "axie-infinity",
  "frax",
  "elrond-egld",
  "aave",
  "trueusd",
  "zcash",
  "eos",
  "bitcoin-sv",
  "hedera-hashgraph",
  "okb",
};

AssetCoin currentCoinTrade = AssetCoin();
String sessionToken = "";
User currentUser = User();
bool isActivated = false;
